# **Chart_Studio Plotly + Cufflinks**
___
___

***Topics***



*   **Frequency Bar Plot** *(Example: How many times any name (groupby) appeared in a column)*
*   **Total Bar Plot** *(Example: Total sum of money based on each name (groupby))*
*   **Normal Bar Plot** *(Example: Price for each car)*
*   **Multi-Column Normal Bar Plot** *(Example: what are the asking prices of same car in two different shops)*

In [ ]:
!pip install cufflinks chart_studio plotly

**Import List**

In [2]:
# plotly imports
import plotly.graph_objs as go
import chart_studio.plotly as py
# Cufflinks wrapper on plotly
import cufflinks as cf

import pandas as pd
import numpy as np

%matplotlib inline

# Options for pandas
pd.options.display.max_columns = 30

# Display all cell outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

## Initializations

**This function is required for GOOGLE COLAB plotly view**
Need to call the following line in **every cell** if it contains vizualization code

`configure_plotly_browser_state()`

`init_notebook_mode(connected=False)`

In [3]:
def configure_plotly_browser_state():
  import IPython
  display(IPython.core.display.HTML('''
        <script src="/static/components/requirejs/require.js"></script>
        <script>
          requirejs.config({
            paths: {
              base: '/static/base',
              plotly: 'https://cdn.plot.ly/plotly-latest.min.js?noext',
            },
          });
        </script>
        '''))

In [4]:
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)
cf.go_offline(connected=True)

# Set global theme
cf.set_config_file(world_readable=True, theme='pearl')

## DATA

In [10]:
df = pd.read_csv('census.csv')
df = df[df['SUMLEV'] == 50]
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,...,RINTERNATIONALMIG2011,RINTERNATIONALMIG2012,RINTERNATIONALMIG2013,RINTERNATIONALMIG2014,RINTERNATIONALMIG2015,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,55253,55175,55038,55290,55347,...,0.363924,0.289782,0.290347,0.326300,0.343466,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,186659,190396,195126,199713,203709,...,1.011215,0.912334,0.881921,1.073855,1.095627,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,27226,27159,26973,26815,26489,...,-0.146609,-0.257424,-0.110840,-0.074366,0.000000,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,22733,22642,22512,22549,22583,...,0.438654,0.705234,0.797272,0.932070,0.930604,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,57711,57776,57734,57658,57673,...,0.052136,0.329041,0.346290,0.485302,0.485559,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

In [11]:
df.describe()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,NPOPCHG_2010,NPOPCHG_2011,...,RINTERNATIONALMIG2011,RINTERNATIONALMIG2012,RINTERNATIONALMIG2013,RINTERNATIONALMIG2014,RINTERNATIONALMIG2015,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
count,3142.0,3142.000000,3142.000000,3142.000000,3142.000000,3.142000e+03,3.142000e+03,3.142000e+03,3.142000e+03,3.142000e+03,3.142000e+03,3.142000e+03,3.142000e+03,3142.000000,3142.000000,...,3142.000000,3142.000000,3142.000000,3142.000000,3142.000000,3142.000000,3142.000000,3142.000000,3142.000000,3142.000000,3142.000000,3142.000000,3142.000000,3142.000000,3142.000000
mean,50.0,2.668682,5.192553,30.280076,103.572884,9.826204e+04,9.826802e+04,9.845540e+04,9.921033e+04,9.996901e+04,1.007089e+05,1.014982e+05,1.022975e+05,187.383195,754.931254,...,0.963157,1.059560,1.064171,1.206725,1.239492,-1.670721,-2.579837,-1.321452,-2.307488,-1.384129,-0.707563,-1.520276,-0.257281,-1.100763,-0.144637
std,0.0,0.803149,1.964060,15.144339,107.704060,3.129467e+05,3.129583e+05,3.135478e+05,3.167040e+05,3.199686e+05,3.231351e+05,3.262347e+05,3.292097e+05,796.741665,3847.284814,...,1.588162,1.906898,1.695318,1.855839,1.905114,10.479885,11.948278,12.268314,11.512543,12.380406,10.681113,12.299923,12.275591,11.537218,12.339410
min,50.0,1.000000,1.000000,1.000000,1.000000,8.200000e+01,8.200000e+01,8.300000e+01,9.000000e+01,8.100000e+01,8.900000e+01,8.700000e+01,8.900000e+01,-5442.000000,-13926.000000,...,-0.895456,-3.787879,-1.121705,-0.907853,-0.856688,-128.205128,-147.727273,-109.876862,-178.947368,-84.844838,-128.205128,-147.727273,-102.988031,-178.947368,-62.322703
25%,50.0,2.000000,4.000000,18.000000,35.000000,1.111450e+04,1.111450e+04,1.108775e+04,1.108175e+04,1.101500e+04,1.103375e+04,1.099500e+04,1.098600e+04,-19.000000,-91.750000,...,0.107218,0.107352,0.129411,0.170373,0.174980,-6.204546,-7.629136,-6.444499,-7.410370,-6.773510,-5.487819,-6.943265,-5.568782,-6.321287,-5.623333
50%,50.0,3.000000,5.000000,29.000000,79.000000,2.587200e+04,2.587200e+04,2.584600e+04,2.579050e+04,2.583400e+04,2.574800e+04,2.568950e+04,2.569850e+04,7.000000,7.500000,...,0.458653,0.440731,0.493090,0.585486,0.595054,-1.605021,-2.664319,-1.857368,-2.019618,-2.046162,-0.746070,-1.676233,-0.880087,-0.990431,-0.935521
75%,50.0,3.000000,7.000000,45.000000,133.000000,6.678000e+04,6.678050e+04,6.691225e+04,6.688500e+04,6.709950e+04,6.749425e+04,6.770050e+04,6.752750e+04,77.750000,220.500000,...,1.190459,1.205907,1.299550,1.511478,1.549393,2.909174,2.588470,3.392461,3.320646,3.792381,4.010888,3.904147,4.676683,4.544616,4.981018
max,50.0,4.000000,9.000000,56.000000,840.000000,9.818605e+06,9.818700e+06,9.826009e+06,9.896602e+06,9.970436e+06,1.004518e+07,1.010944e+07,1.017029e+07,15111.000000,73051.000000,...,24.910478,40.908521,23.009385,23.827477,23.730850,101.123596,119.193807,239.130435,146.367943,281.407035,101.123596,119.861185,239.130435,146.960126,281.407035

## **Frequency Bar Plot(Total times a name appeared)**

In [ ]:
####### These Lines are important for Google Colab ######
configure_plotly_browser_state()
init_notebook_mode(connected=False)
####### Without these lines figure will be null ######

df.groupby('STNAME').count()['SUMLEV'].iplot(
    kind='bar', yTitle='Total Row frequency', linecolor='black', title='Total Rows related to States')

⚠️*Comment: `.count()` function is used. That is why frequency *

## **Total Bar Plot (Total sum for a single values)**

In [ ]:
####### These Lines are important for Google Colab ######
configure_plotly_browser_state()
init_notebook_mode(connected=False)
####### Without these lines figure will be null ######

df.groupby('STNAME').sum()['CENSUS2010POP'].iplot(
    kind='bar', yTitle='Total Population', linecolor='black', title='Population by Sates')

⚠️*Comment: `sum()` function is used that is why total population is calculated based on state (groupby)*

## **Normal Bar Plot**

In [15]:
df = pd.read_csv('census.csv')
df = df[df['SUMLEV'] == 40]
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,...,RINTERNATIONALMIG2011,RINTERNATIONALMIG2012,RINTERNATIONALMIG2013,RINTERNATIONALMIG2014,RINTERNATIONALMIG2015,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,4801108,4816089,4830533,4846411,4858979,...,1.027720,1.019840,1.002216,1.142716,1.179963,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
68,40,4,9,2,0,Alaska,Alaska,710231,710249,714021,722720,731228,737442,737046,738432,...,2.104763,3.764921,3.157959,3.167201,3.525637,-1.173489,-1.946424,-3.915107,-14.438910,-10.407475,0.931274,1.818497,-0.757148,-11.271709,-6.881838
98,40,4,8,4,0,Arizona,Arizona,6392017,6392307,6408208,6468732,6553262,6630799,6728783,6828065,...,1.962889,2.091538,2.218133,2.541397,2.558707,1.327489,5.245740,3.905473,6.219955,6.776501,3.290378,7.337279,6.123606,8.761352,9.335208
114,40,3,7,5,0,Arkansas,Arkansas,2915918,2915958,2922394,2938538,2949499,2957957,2966835,2978204,...,0.960939,1.078798,1.124342,1.287134,1.309663,1.365312,-0.432402,-0.442153,-1.060966,-0.407735,2.326251,0.646395,0.682189,0.226168,0.901928
190,40,4,9,6,0,California,California,37253956,37254503,37334079,37700034,38056055,38414128,38792291,39144818,...,3.910168,3.810915,4.068514,4.606197,4.637637,-1.148464,-1.163788,-1.339869,-0.862856,-1.981572,2.761704,2.647127,2.728645,3.743342,2.656065

In [ ]:
####### These Lines are important for Google Colab ######
configure_plotly_browser_state()
init_notebook_mode(connected=False)
####### Without these lines figure will be null ######

df2 = df[['STNAME','ESTIMATESBASE2010']].set_index('STNAME')

df2.iplot(kind='bar', xTitle='State', yTitle='Estimated Base Population',
    title='Estimated Base Population by 2010')

⚠️*Comment: Estimated Population for Alabama 4.78M*

`Needed to **set state as X-Axis**`

## **Multi-Column Comparrision using Normal Bar Plot**

In [ ]:
####### These Lines are important for Google Colab ######
configure_plotly_browser_state()
init_notebook_mode(connected=False)
####### Without these lines figure will be null ######

df2 = df[['STNAME','POPESTIMATE2010','POPESTIMATE2015']].set_index('STNAME')

df2.iplot(kind='bar', xTitle='State', yTitle='Estimated Population',
    title='Estimated Population comparrison between 2010 & 2015')